name: Deploy
on:
    push:
        branches:
            - master
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "17"
            - run: npm install yarn -g
            - run: yarn
            - run: yarn build
